image_width: 1440
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [3642.29831,    0.     ,  575.70098,
            0.     , 3654.06668,  488.92598,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.088784, -0.289940, -0.014053, -0.012831, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [3657.36646,    0.     ,  569.91743,    0.     ,
            0.     , 3673.44653,  484.09362,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]