/**:
  ros__parameters:
    debug: true
    target_frame: odom
    max_armor_distance: 10.0

    ekf:
      sigma2_q_x: 0.009
      sigma2_q_y: 0.009
      sigma2_q_z: 0.009
      sigma2_q_yaw: 1.1
      sigma2_q_r: 80.0

      r_x: 45e-5
      r_y: 45e-5
      r_z: 45e-5
      r_yaw: 75e-5

    tracker:
      max_match_distance: 0.5
      max_match_yaw_diff: 0.7

      tracking_thres: 2
      lost_time_thres: 1.5
    
    solver:
      prediction_delay: 0.0
      controller_delay: 0.0
      min_switching_v_yaw: 1.0
      max_tracking_v_yaw: 60.0 #转速(rad/s)大于这个值时瞄准机器人中心
      shooting_range_height: 0.135
      shooting_range_width: 0.135
      side_angle: 16.0 
      bullet_speed: 15.0
      compenstator_type: "ideal"
      gravity: 9.82
      resistance: 0.092
      iteration_times: 20 # 补偿的迭代次数
      # ["距离下限, 距离上限, 高度下限, 高度下限, pitch轴补偿值"]
      angle_offset: [
        "1.0 8.0 -10000.0 10000.0 0.0 0.0"
      ]
