image_width: 1440
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [2372.99817,    0.     ,  701.71273,
            0.     , 2367.32254,  549.08331,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.109255, 0.226181, -0.000305, 0.001669, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [2353.61646,    0.     ,  702.60943,    0.     ,
            0.     , 2355.28312,  549.05565,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]