image_width: 1440
image_height: 1080
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [2362.17624,    0.     ,  726.47807,
            0.     , 2354.2404 ,  536.30476,
            0.     ,    0.     ,    1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.116381, 0.096836, -0.004415, 0.002386, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [2336.86475,    0.     ,  727.74633,    0.     ,
            0.     , 2337.94775,  534.0879 ,    0.     ,
            0.     ,    0.     ,    1.     ,    0.     ]